== 针对iOS系统采取的安全措施

iOS系统总体上是相当安全的，无论是iOS系统的设计还是对App的审核都对非常重视安全和隐私。

很多App由于其自身的特点对安全与隐私要求不高，对这些App来说iOS系统自身的安全措施已经足够，不用考虑太多。然而一些App比如手机银行、比特币钱包等会对安全和隐私有更高的要求，这就要求需要额外考虑一些情况。

=== iOS系统的一些安全隐患

iOS系统的一些行为有可能会无意中把一些用户的敏感信息保存到手机的文件中。比如当App进入后台时系统会把屏幕快照保存下来，以便于返回前台时显示一个过渡动画。还有其他的比如网络缓存、键盘输入缓存等。正常情况下这些文件在沙箱机制的保护之下，是安全的，其他App无法访问。但是当某个App、某个系统进程存在安全漏洞且漏洞被利用时，这些文件就有可能被恶意程序访问，带来安全与隐私问题。比如历史上iOS系统上的Safari浏览器和短信程序都出现过漏洞，黑客可以利用这些漏洞获取手机上的文件。

由于比特币钱包对安全与隐私要求比较高，BasicBitcoinWallet针对以上情况采取了一些的措施，以尽可能保证资金的安全与用户的隐私。

=== 所采取的主要措施

1.加密重要的数据

2.处理可能带来数据泄漏的多种情况

3.重要数据只保存到设备本地，不会被同步到iCloud云端

=== 措施的具体实现

{empty}1. 重要数据存储在iOS系统的keychain中

* keychain是iOS系统提供存储重要数据的数据库，被iOS的数据保护机制所保护。
其本身保存的数据就是加密过的。但进一步的，BasicBitcoinWallet会把钱包助记词序列，根种子、扩展公钥、PIN码等信息先用AES加密算法加密，然后再存储在keychain中。

* 保存数据项时设置了UICKeyChainStoreAccessibilityWhenUnlockedThisDeviceOnly属性。当设备被锁定时，无法访问这些数据项。另外这些数据项也不会被同步到iCloud

{empty}2.
钱包退到后台时，会用一个页面来遮挡当前页面，这样就可以防止敏感信息被截图保存到设备上。

{empty}3. 禁用第三方键盘

iOS系统允许用户使用第三方实现的键盘扩展，这可以满足用户个性化的要求，但也带来了安全隐患，第三方可能会记录用户的输入，然后发到远程的服务器上，如果他们只是分析数据用以改进产品还好，但如果他们怀有恶意，就会构成安全与隐私威胁。比如用户恢复钱包的时候会输入钱包助记词，如果第三方窃取了所输入的词，就等于获取了钱包上比特币的使用权。

{empty}4.
使用地址拷贝功能时会提醒用户。iOS通用剪贴板是所有应用程序共享的，当用户拷贝一个比特币地址时，设备上的其它App都有能力有读该地址的文本，这样就可能会泄漏用户的隐私。BasicBitcoinWallet允许用户拷贝地址，但在拷贝之前会先提醒用户让用户确认。

{empty}5. 禁用输入框的自动补全功能。

输入框自动补全功能会记录用户输入过的字母，这可能会造成数据泄漏。在BasicBitcoinWallet中禁止了一些输入框的自动补全功能，比如输入用户助记词页面的输入框就被禁止了此功能。

6.禁用网络缓存

iOS出于性能考虑，默认情况下应用程序的网络请求结果都会被缓存，这些缓存可能会泄漏用户的隐私（比如钱包的交易数据）。在BasicBitcoinWallet中禁用了系统网络缓存（不会影响其它应用）。

7.交易数据的保护措施

通过网络请求的交易数据会作为数据文件保存到本地。由于交易数据涉及到用户隐私，为了保护用户隐私做了以下处理：

* 保存前先用AES加密。

* 使用iOS
系统文件保护API，把交易数据文件的保护等级设置为最安全的Complete级别。在这个等级下，锁屏之后就无法读取该文件。

* 设置文件属性，使该文件不会被备份到iCloud.

[TIP]

====

以上的具体实现，都可以在代码里通过搜索for security 或者 for privacy 搜到。

====

=== 以上措施的局限性

安全是一个非常繁杂的领域，涉及到的知识点很多。而且安全只是相对的，因为总是不断有新的漏洞被发现、被利用。

以上的安全措施都可以在一定程度上降低数据泄漏的风险。但如果手机被其他人获得且可以进入系统，且对方懂得逆向开发的知识，对方就可以通过逆向开发的一些手段（比如在iOS下写tweak）来获得钱包的使用权。这种情况所能采取的一切措施也只能是给这个过程设置些障碍，延缓破解的过程。所以设置足够安全的系统锁屏密码，让别人即使获得手机也无法进入系统也非常重要。

如果想了解更多关于iOS系统安全方面的知识可以参考：link:RecommenedMaterial.adoc#iOSSecurityRelated[推荐材料#iOS安全相关]
