
== 网络实现方式
由于移动设备存储有限，移动端比特币钱包无法用全结点的方式来实现，一般在SPV和Web
API这两种方式之间做选择。

相比较全节点，这两种方式没有同步全部区块链数据，比全节点隐私性更弱。关于比特币的隐私性是一个很大的话题，这里只做简单的说明。

暴露隐私主要包括：比特币地址与IP地址之间的关联被发现；比特币地址之间的关联被发现（比如多个比特币地址被发现属于同一个用户）；比特币地址与某人真实身份的关联被发现。等等。

想了解更多比特币隐私的相关知识可以参考
《区块链：技术驱动金融》第6章“比特币和匿名性”与Bitcoin
Wiki中Privacy页面 https://en.bitcoin.it/wiki/Privacy

=== 实现方式的比较

一、SPV方式

优点是符合比特币去中心化思想，无需信任某一个中心服务。

缺点是：

1. 相比全结点隐私性弱。虽然有了BIP-37这种旨在保护用户隐私的方案，但在实际中人们发现BIP-37方案有缺陷，如果有人刻意监控钱包的网络访问，仍然会暴露地址信息。

2. 不能立刻使用，使用前需要先下载区块链头。

二、Web API方式

Web API的服务是在全节点基础之上实现了可以方便使用的API。

Web API可以是第三方提供的，也可以自己搭建（比如使用开源代码自己搭建）

{empty}1. 
使用第三方服务提供的Web API的优点是：

* 可以立刻使用，方便快捷。

* Web API往往提供了方便使用的接口，客户端实现起来简单。

缺点是：

* 中心化，需要信任第三方服务。在隐私方面，要信任第三方。因为前面提到的隐私都是直接暴露给第三方服务的（隐私性类似于传统的中心式互联网服务）。

* 第三方是否一直提供稳定的服务是我们决定不了的。（比如某个提供第三方服务的公司不再提供该服务了）

{empty}2. 
自己搭建Web API可以保护隐私，客户端实现也简单，但需要自己运行服务。

=== 目前采用的方式

BasicBitcoinWallet目前是使用Web API的方式，使用我搭的一个服务（目前只支持testnet)。服务的代码是一个开源项目，我在原来代码的基础上进行了少量修改（ https://github.com/lianxianghui/electrs ）。

如果用户关注隐私性，也可以使用该代码自己搭服务，然后把BasicBitcoinWallet中访问Web Api的IP指向设为该服务的IP或域名。

关于更多比特币网络的相关知识，可以参考 https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch08.asciidoc
和
https://programmingblockchain.gitbook.io/programmingblockchain/wallet （这里说明了比特币钱包的不同联网方式。这本网络教程虽然是用C#，但相关知识的通用的）


