== 安全与隐私

掌握了比特币的私钥，就等于拥有了比特币。所以保护比特币的安全主要就是保证私钥不泄漏。

私钥的安全有一部分是用户自己的责任，比如把钱包助记词存储到安全的地方、为移动设备设置足够安全的锁屏密码、及时安装系统安全更新等等。另一部分是钱包在设计和实现上采取一些必要的安全措施，以尽量保证私钥的安全。

比特币隐私泄漏主要涉及：用户钱包下的交易、余额等信息泄漏；同一用户的不同比特币地址之间的关联被发现；比特币地址与某人真实身份的关联被发现，等等。（比特币隐私是一个很大的话题，想了解更多比特币隐私的相关知识可以参考
《区块链：技术驱动金融》第6章“比特币和匿名性”与Bitcoin
Wiki中的Privacy页面https://en.bitcoin.it/wiki/Privacy）

== BasicBitcoinWallet的安全与隐私措施

=== 一、在功能设计上的考虑

1.PIN码

用户可以为钱包设置PIN码，PIN码可以防止在其他人获得手机使用权的情况下直接对钱包进行操作。

设置PIN码后：

* 进入钱包时需要输入PIN码(保护隐私）

* 程序进入后台再回到前台时需要输入PIN码（保护隐私）

* 发送比特币、查看钱包助记词、
重置钱包等功能需要输入PIN码才能使用（保护安全）

* 查看扩展公钥时需要输入PIN码（主要是保护隐私）

2.初始化钱包时，可以选择使用助记词密钥，这可以带来额外的安全性。

3.可以初始化成只读钱包（也叫监视钱包）

初始化时，用户可以根据自己的需要来把钱包初始化成全功能或者只读钱包。全功能钱包包含私钥，可以对交易进行签名。只读钱包只存储公钥，不包含私钥，只能接收、查看交易记录。如果用户在某种场景下只需要接收和查看交易记录，可以使用只读钱包。这时候即使只读钱包发生数据泄漏，也只是公钥被暴漏，只会造成交易信息泄漏（是关于隐私的问题），不会导致比特币丢失。

4.重要数据如根种子、扩展公钥、交易数据等都先被加密，然后再保存到设备上。

5.用户可以通过重置钱包来抹掉存储在手机上的密钥、缓存等数据。在用户更换手机前需要使用这个功能来保证这些数据不被其他人获得。（注意：直接删除App，不能保证这些数据会被系统自动删除。）

6.可以通过使用一对[#anchor]####冷钱包与热钱包来达到安全性和便捷性的平衡。

请参考：http://ColdAndHotWallet.adoc/[冷钱包与热钱包 ]

=== 二、针对iOS系统的安全与隐私考虑

请参考：http://iOSRelatedSecurity.adoc/[针对iOS系统采取的安全措施]

== BasicBitcoinWallet[#anchor-1]####网络实现方式与隐私的关系

请参考：[#anchor-2]####http://NetworkConsiderations.adoc/[网络实现方式 ]


