第一次使用钱包时需要进行初始设置。

初始设置包括两方面：一是为了资金安全设置PIN码，二是初始化钱包的根种子或者扩展公钥。

由于初始化过程中的很多页面已经具有了文字描述，所以下面只进行一些必要的说明。

=== 1.初始设置

* 设置PIN码

PIN码的主要作用是：防止其他人获得移动设备使用权时使用钱包，从而造成可能的资金丢失或者隐私泄漏。举个例子：比如在某种情况下您的朋友要临时使用一下您的手机，这时为了隐私您可能不希望他/她无意中看到您钱包里的资金数量，这时PIN码就起到了保护隐私的作用。

设置PIN码后，会在进入钱包、钱包进入后台又返回前台、发送比特币（对交易进行签名）、重置钱包、显示钱包助记词等情况时要求用户输入PIN码。

* 初始化钱包

BasicBitcoinWallet是一个满足BIP-39、部分满足BIP-44标准（为了简化，目前只使用账户0，除了这一点其他都满足）的比特币钱包。(关于比特币钱包相关的标准可以参考 https://wiki.trezor.io/Cryptocurrency_standards )

BIP-39主要说的是通过一个助记词序列来生成钱包根种子。下面引用《精通比特币》这本书中对BIP-39的描述。（翻译来自MasteringBitcoinCn)

    使用一种标准化的方法，从一系列英文单词中创建种子，这些英文单词很容易在钱包之间转录、导出和导入。这称为助记词，BIP-39定义了这个标准。现在，多数比特币钱包（以及其它加密货币的钱包）使用这个标准，并可以使用可互操作的助记词导入和导出种子，以进行备份和恢复。

初始化钱包时如果选择“创建钱包”，首先会生成一个密码学安全随机数（cryptographically
secure random bytes），并显示这个随机数所对应的助记词序列。

初始化钱包时如果选择“恢复钱包”，接下来的过程是输入之前已有的钱包助记词序列。

这个过程可以通过设计稿来了解，主要就是BIP-39标准的具体细节：选择助记词数量、输入可选的助记词密码等。

注意这里的助记词密码不同于PIN码，其作用是增强助记词的安全。用户生成完助记词序列后，需要记录下来保存到安全的地方。如果用户为了进一步的安全，接下来也可以指定一个助记词密码，钱包会使用助记词序列和助记词密码来一同生成钱包所使用的根种子，所以在设置过助记词密码的情况下，即使其他人获得了助记词序列，如果没有助记词密码，也无法恢复钱包。注意这里的助记词密码是要用户记在心里的，不会记录到钱包里，这也意味着在增强安全性的同时也带来一定的风险--如果用户忘记了这个助记词密码，以后就无法恢复钱包了（除非助记词密码较短。这时尝试暴力破解，也许可以找回来）。

上面的两个选项都是会初始化成全功能钱包。

另外还有一个“导入只读钱包”功能。只读钱包(Watch-only，也称为监控钱包）只有扩展公钥，不能生成私钥，所以不能对交易进行签名，其它功能与全功能钱包一样。全功能钱包由于具有根种子，可以生成私钥，所以可以对交易签名。

* 生成钱包

在初始化向导的这一步，用户可以选择生成测试网络(Testnet3)或者主网络(Mainnet)钱包。如果是想试用一下比特币钱包，可以选择测试网络。测试网络上的比特币没有价值，可以去免费申请一些来进行测试（google搜索“获取测试比特币”可以找到申请方法）。

如果一开始用户选择的是创建新钱包，选择完测试网络或者主网络后，就会进入钱包主页面。

如果一开始选择的是恢复钱包，还要进入“搜索地址并生成”页面。

[[搜索地址并生成]]
* 搜索地址并生成

如果用户是在恢复钱包，钱包不仅要根据用户输入的钱包助记词(和可选的助记词密码）来生成钱包根种子，还需要搜索当前钱包的哪些地址具有比特币，即哪些地址具有UTXO（未消费交易输出）。这就需要连接网络搜索（如果是打算作为冷钱包使用，不要搜索，选择“仅生成”）。

搜索步骤大概如下：

根据BIP-44标准生成地址，从接收地址0开始使用20个连续的地址，从比特币网络获取这些地址相应的交易信息，如果获取到的交易包含了某个已发送地址，就把该地址记录为已使用。然后继续发送20个地址，一直到从某个地址开始的20个连续地址都没有交易信息，则认为从这个地址开始以后的地址都没有被使用过（这只是搜索过程的大概描述，具体可以参考 https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Account_discovery ）。注意由于BasicBitcoinWallet目前只使用账户0，所以只搜索账户0下的地址。如果用户正在恢复的钱包包含了其它账户，目前不会显示出来（但不会导致资金丢失）。

搜索完成之后，就会进入钱包主界面。


