发送比特币分三个步骤：构造交易、对交易签名、广播已经签名的交易到比特币网络。

=== 1.构造交易

* 发送比特币页面的选项

在“发送比特币”页面可以看到有两个构造比特币交易的选项：输出固定、手动选择输入；输入固定。

在该页面上有对这两个选项的文字描述，这里就不再重复。

这里需要说明的是，大部分比特币钱包并没有这样的选项，只是允许用户输入接收地址和要发送的数量
（可以输入一个数值或者选择全部）。这是因为大部分比特币钱包为了易用性，把内部发生的事隐藏了。其实BasicBitcoinWallet也可以加一个选项：输出固定、自动选择输入。这其实就相当于大部分钱包所实现的功能。只是因为BasicBitcoinWallet的设计是希望用户更多的了解比特币钱包的细节、更多了解在进行一个操作时钱包内部到底发生了什么，所以就没有实现这样的功能。

[[let_user_know_utxo]]

* 让用户知道UTXO

UTXO是
“未花费交易输出”的意思。如果把比特币钱包和我们平时用的钱包（以下称之为实体钱包）做比较的话，一个UTXO就类似于实体钱包里一张面额为xx元的纸币现金。全部的UTXO就类似实体钱包里全部现金。UTXO与纸币的区别是，它的面额是不固定的，所以它更类似于支票。

BasicBitcoinWallet在设计的时候，使用了这样的类比，就像一个人打开实体钱包可以查看钱包里有多少钱一样，BasicBitcoinWallet可以显示目前钱包里有哪些UTXO，每个UTXO包含的比特币是多少，所有UTXO的值加到一起有多少（即钱包当前余额）。

使用BasicBitcoinWallet发送比特币时，也使用了这样的类比。比如一个人想从实体钱包支出一笔钱时，先确定要支出多少钱，然后打开钱包，选择一张或几张纸币，拿出来给对方，同时如果这些纸币总额大于实际要支出的钱时，会期望对方找零。使用BasicBitcoinWallet发送比特币时（以输出固定、手动选择输入为例），是先确定接收地址和金额，以此来构造交易输出，然后选择一个或几个UTXO来构造交易输入，最后根据选中的UTXO总值和发送金额来决定是否需要找零，如果需要的话会构造找零输出。（以上为了简化描述未提及交易费，实际上构造交易的过程还需要考虑交易费）

* 手续费

用户在构造交易的时候需要考虑手续费。目前比特币钱包多采用动态估算手续费的方式来自动计算搜续费。

BasicBitcoinWallet实现了动态估算手续费。用户可以从第三方交易费估算服务提供的三个费率选项中选一个，也可以自己指定一个手续费率（适用于高级用户）。

费率会影响比特币矿工在打包交易时的处理优先级。如果某个交易的手续费率太低，该交易可能会被推迟处理，或者根本不被处理，也就是该交易可能很长时间都不到账。

第三方交易费估算服务提供的几个费率选项分别是：

**fastestFee**:
能使交易得到最快确认（通常只有0到1个区块的延迟）的最低费率 +
**halfHourFee**: 能使交易在半小时内得到确认（90%概率）的最低费率 +
**hourFee**: 能使交易在一小时内得到确认（90%概率）的最低费率

一般情况下费率高到账就快，但手续费也高，费率低到账就慢，但手续费低。用户可以根据自己的需要来选择。

关于更多手续费的相关知识可以参考 https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch06.asciidoc#transaction-fees

* 输出固定，手动选择输入

这种方式是先确定输出，然后再根据输出和交易手续费来选择输入。

比如确定要给某个地址转
0.001BTC的比特币，这时点先“输出固定，手动选择输入”按钮进入“构建固定输出交易”页面。

进入页面后分三个步骤构造交易：

1）选择或输入手续费率

2）添加交易输出

点“选择输出”进入“输出列表”页面，点“添加输出”按钮进入“添加输出”页面。这时候点“点击添加”来添加接收地址(目前接收地址支持P2PKH、P2SH两种地址类型，暂不支持其它类型），然后在数量栏输入0.001，最后点“确定”会回到“输出列表”页面。这时可以看到已经成功添加了一个输出。点“确定”回到“构建固定输出交易”页面。这时添加输出就完成了。

3）添加交易输入

点“选择输入”进入“选择输入（UTXO）”页面。在这个页面可以看到目前已有的UTXO(未花费交易输出），按着面额从大到小列出。这时可以根据页面上方的提示来选择一个或几个UTXO来满足刚才已添加的输出金额。这时你可能会发现页面上方的提示的比如“至少需要选择总额为0.0010192BTC的输入”，这里要求的数值（比如0.0010192）大于刚刚添加的输出的数值0.001。这是因为自动估算了手续费

（估算的手续费=选择的手续费率*估计的交易字节数）。

根据提示选择完足够金额的UTXO作为正在构造的交易的输入后，点“确定”会返回“构建固定输出交易”页面，回到该页面时往往会弹出一个对话框询问“是否添加找零？”，这是因为所选择的UTXO的总和往往是大于输入值与估算的交易费的值之和，多出来的部分就要找零。选择“是”添加找零。这时会自动添加一个找零输出。找零的金额会自动计算，接收地址自动选择本地第一个尚未使用的找零地址。这样添加交易输入就完成了。

完成了上面三个步骤，可以从“构建固定输出交易”
页面看到所构造交易的输入、输出和手续费。如果没有问题就可以点击右上角的“下一步”按钮，进入交易信息页面，至此（未签名）交易构造完成。

=== 2.对交易签名

在发送交易之前必须要对交易进行签名。这里的发送是指把交易数据广播到比特币网络上。

这里签名的目的就是要证明构造交易的人拥有花费一个输入（也就是UTXO)的权利。

关于签名的原理和细节需要了解的知识比较多，如果想更深入了解可以参考: https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch06.asciidoc#digital-signatures-ecdsa

在“交易信息”页面的下面有三个按钮，对应三个功能：查看未签名交易文本、查看签名交易文本、签名并发送。点“签名并发送”按钮就直接完成了这次发送比特币的操作。但如果想了解更多交易数据的细节。可以分别点“查看未签名交易文本”按钮和“查看签名交易文本”按钮来查看未签名时交易的交易数据和签名后的交易数据。未签名交易文本和已签名交易文本主要差别在“scriptSig”字段，在未签名交易文本中这个字段是锁定脚本(locking
script)，已签名交易文本中这个字段是与锁定脚本对应的解锁脚本( unlocking
script)

=== 3. 广播已经签名的交易到比特币网络

点击“交易信息”页面“签名并发送”按钮和“签名交易文本”页面的“发送”按钮都会把已经签名的交易广播到比特币网络上。（目前是push到第三方服务器上，由第三方服务器来广播到比特币网络上。关于BasicBitcoinWallet的网络实现请参考： link:NetworkConsiderations.adoc/[网络实现方式
]）
